### PR TITLE
[chg] populate email field atuomatically

### PR DESCRIPTION
**Pull request by daniele-andreotti**
Automatically returns user email or a standard email value (required by validation)

### CODE REVIEW

**Review by mauritsvanrees — COMMENTED** [review]
Seems fine, though I have not tried it (and will not do so).
I would remove the `test@test.test` though, and go for an empty string then.
The "test@test.test" sounds more something for a placeholder, and I don't know from the top of my head if you can set a placeholder in forms.

**Comment by daniele-andreotti** [comment]
Hi,
I tried and it worked. There is a validation check for email format which does not let pass empty values, if I remember well.

**Comment by mauritsvanrees** [comment]
So this field is effectively required, even though it is not marked as such? Ah well.
I would still say it is up to the user to set an email address if we cannot automatically determine one. I would prefer a validation error over a bad email value.

**Comment by daniele-andreotti** [comment]
Ok, that's fine, I will remove the default value.

**Pull request merged**
